### ISSUE TITLE
Precisions for the User Guide

### ISSUE THREAD

**Issue by Rubbens** [Rubbens/4Me-Documentation#3]
- La page est rafraîchie automatiquement toutes les xx secondes.
  Can you confirm the refresh frequence on the client?

Fonctionnement Dégradé : Would you mind to add an imager pic for this one?

**Comment by kouak** [comment]
There is no refresh sequence on the client. Everything happens in realtime.

When a client performs an XMAN action, said action is is received right away by the backend and is propagated to the other clients.

Same thing for the mapping part, and the flight history in the arcid component.
